### ISSUE TITLE
The Things Stack Community Edition (V3) - Not working :( 

### ISSUE THREAD

**Issue by alexcorvis84** [TTNApeldoorn/sound-sensor#2]
Hello,

I used this project and got it working on The Things Network V2.

Now, I've migrated it to The Things Stack Community Edition (V3) and I can't get it working. 

My question is, have you been able to test it with V3? Do I need to change some settings in code to get it working in V3? 

The sensor tries to make Join Request/Join Accept, but when it comes to sending the payload, it does not manage to do so correctly.

Any help would be much appreciated :) 

Many thanks in advance for sharing the project!

![image](https://user-images.githubusercontent.com/44984326/124351102-c0537780-dbf8-11eb-849f-b0eeee39a565.png)

![image](https://user-images.githubusercontent.com/44984326/124351128-dd884600-dbf8-11eb-8680-20b87c27b02f.png)

![image](https://user-images.githubusercontent.com/44984326/124351147-ef69e900-dbf8-11eb-8bd0-7521c9b253a0.png)

**Comment by alexcorvis84** [comment]
Hi @pe1mew 

Not sure why (might be related with issues on TTSCE? 🤷‍♂) but the thing is that after a few hours, sensor successfully joined and now it's working fine 😃 on V3. So you can proceed to close this issue (apologies).

I took the opportunity to update the payload decoder to make it compatible with V3, so I've just submitted a PR.

Regards

![image](https://user-images.githubusercontent.com/44984326/124361707-c36a5a00-dc30-11eb-9998-8e8dc4e7159e.png)

**Comment by pe1mew** [comment]
Good to hear you got it working. Thanks for your contribution
